"""add_invoice_and_quota_settings

Revision ID: aeef2bf47edd
Revises: 9c011ebeb1d9
Create Date: 2026-05-28 17:44:02.101890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeef2bf47edd'
down_revision: Union[str, Sequence[str], None] = '9c011ebeb1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
