"""add advanced scraper columns

Revision ID: b398b3af8049
Revises: 
Create Date: 2026-05-28 12:30:46.992439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b398b3af8049'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('url_template', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('proxy_enabled', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('proxy_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'proxy_country')
    op.drop_column('sources', 'proxy_enabled')
    op.drop_column('sources', 'url_template')
    # ### end Alembic commands ###
